---------------------------------------------------------------------------
--                        DO NOT MODIFY THIS FILE                        --
--                                                                       --
-- The following content is generated by JPA according to entity classes --
---------------------------------------------------------------------------
CREATE
    SEQUENCE public.user_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE public.user_profile_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    TABLE
        public.avatar(
            id INTEGER DEFAULT nextval('avatar_id_seq') NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        public."user"(
            id INTEGER NOT NULL,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            deleted_at TIMESTAMP(6) WITH TIME ZONE,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            email text NOT NULL,
            hashed_password text NOT NULL,
            username text NOT NULL,
            PRIMARY KEY(id),
            CONSTRAINT IDX_78a916df40e02a9deb1c4b75ed UNIQUE(username),
            CONSTRAINT IDX_e12875dfb3b1d92d7d7c5377e2 UNIQUE(email)
        );

CREATE
    TABLE
        public.user_profile(
            avatar_id INTEGER NOT NULL,
            id INTEGER NOT NULL,
            user_id INTEGER NOT NULL UNIQUE,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            deleted_at TIMESTAMP(6) WITH TIME ZONE,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            intro text NOT NULL,
            nickname text NOT NULL,
            CONSTRAINT IDX_51cb79b5555effaf7d69ba1cff PRIMARY KEY(id)
        );

CREATE
    SEQUENCE microteams.message_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microteams.team_machine_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microteams.team_member_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microteams.team_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microteams.thread_member_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microteams.thread_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    TABLE
        microteams.agent_screen(
            agent_user_id BIGINT NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            team_id BIGINT,
            driver VARCHAR(32) NOT NULL,
            sid VARCHAR(32) NOT NULL,
            machine_id VARCHAR(64) NOT NULL,
            session_id VARCHAR(64),
            token VARCHAR(64) NOT NULL,
            cwd VARCHAR(1024),
            PRIMARY KEY(sid)
        );

CREATE
    TABLE
        microteams.machine(
            created_at TIMESTAMP(6) NOT NULL,
            machine_id VARCHAR(64) NOT NULL,
            token VARCHAR(128) NOT NULL UNIQUE,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY(machine_id)
        );

CREATE
    TABLE
        microteams.machine_auth_code(
            created_at TIMESTAMP(6) NOT NULL,
            team_id BIGINT,
            status VARCHAR(16) NOT NULL,
            code VARCHAR(64) NOT NULL,
            machine_id VARCHAR(64),
            machine_name VARCHAR(255) NOT NULL,
            PRIMARY KEY(code)
        );

CREATE
    TABLE
        microteams.message(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            edited_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            sender_id BIGINT NOT NULL,
            thread_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            content TEXT NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microteams.team(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microteams.team_machine(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            team_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            machine_id VARCHAR(64) NOT NULL,
            PRIMARY KEY(id),
            CONSTRAINT uq_team_machine UNIQUE(
                machine_id,
                team_id
            )
        );

CREATE
    TABLE
        microteams.team_member(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            team_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            user_id BIGINT NOT NULL,
            ROLE VARCHAR(255) NOT NULL CHECK(
                ROLE IN(
                    'OWNER',
                    'ADMIN',
                    'MEMBER'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microteams.thread(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            title VARCHAR(255),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microteams.thread_member(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            thread_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            user_id BIGINT NOT NULL,
            ROLE VARCHAR(255) NOT NULL CHECK(
                ROLE IN(
                    'MEMBER',
                    'ADMIN',
                    'OWNER'
                )
            ),
            PRIMARY KEY(id),
            UNIQUE(
                thread_id,
                user_id
            )
        );

CREATE
    INDEX IDXgq97fo5233iohf7rnfx89ypne ON
    microteams.agent_screen(machine_id);

CREATE
    INDEX IDXoqu2lah1ibtqtc2j0j12vyr1j ON
    microteams.agent_screen(agent_user_id);

CREATE
    INDEX idx_message_thread_created ON
    microteams.message(
        thread_id,
        created_at
    );

CREATE
    INDEX IDXg2l9qqsoeuynt4r5ofdt1x2td ON
    microteams.team(name);

CREATE
    INDEX IDXa6y5tmsgcryqujws87w8i5dj9 ON
    microteams.team_machine(machine_id);

CREATE
    INDEX IDX6vonaycb4y376lymvg7mlq2l8 ON
    microteams.team_machine(team_id);

CREATE
    INDEX IDX5g0c914cuohcnat68yxga0pn0 ON
    microteams.team_member(team_id);

CREATE
    INDEX IDX5cxwd5p05k1umbxdo1t50xhfy ON
    microteams.team_member(user_id);

ALTER TABLE
    IF EXISTS public.user_profile ADD CONSTRAINT FKo5dcemd97atrmjapi9x4s1j32 FOREIGN KEY(avatar_id) REFERENCES public.avatar;

ALTER TABLE
    IF EXISTS public.user_profile ADD CONSTRAINT FKqcd5nmg7d7ement27tt9sf3bi FOREIGN KEY(user_id) REFERENCES public."user";
