/*
 *  Description: Turns a finished vite build into a launcher-started one.
 *
 *               The one request that cannot be spread across network paths is the first: a browser
 *               opening a URL knows one host. So that document is made as small as possible and
 *               given one job — register the worker, carry the line registry inline, and start the
 *               real entry point. Everything after it comes from the cache or from whichever line
 *               is fastest, and the domain the user typed stops mattering.
 *
 *               What this file decides, because a library cannot: which of our artefacts are worth
 *               precaching, and what counts as a version.
 *
 *  Author(s):
 *      agent3
 */

import { createHash } from "node:crypto";
import { access } from "node:fs/promises";
import { copyFile, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";

import { buildLauncher } from "@micro-teams/multipath";

/**
 * The startup set, not everything the build emits.
 *
 * `dist/` is ~6.6MB, nearly all of it lazily-loaded chunks (diagram renderers and the like) that
 * nothing needs in order to start. Precaching all of it would spend a user's first visit
 * downloading things they may never open, to buy an offline capability for features that are not
 * the point. What has to be on disk is what the app cannot start without: the entry module, the
 * stylesheet, and the two icon files the shell references.
 *
 * Fonts are deliberately out for the same reason — 2MB, and without them text renders in a fallback
 * face rather than not at all.
 */
/** Where the Web App Manifest is served from — public/manifest.webmanifest, copied by vite. */
const MANIFEST_URL = "/manifest.webmanifest";
/** Matches --background in index.css and background_color in the manifest. */
const THEME_COLOR = "#060606";

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

export function startupManifest(indexHtml) {
  const entry = indexHtml.match(/<script[^>]+src="([^"]+)"/)?.[1];
  const styles = [...indexHtml.matchAll(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"/g)].map(
    (m) => m[1],
  );
  if (!entry) throw new Error("no entry script found in index.html — did the build change?");
  // "/" first, and it is not an afterthought: without the launcher document itself on disk, an
  // offline start has nothing to open — every asset is cached and the browser never gets far enough
  // to ask for one. A real browser found this; nothing else would have.
  //
  // Separate lists, not one: the stylesheets also have to be linked from the launcher document, and
  // deriving them back out of a flat manifest is how /favicon.svg ended up as a stylesheet once.
  // The web app manifest joins them: an installed window opens start_url from this cache, and a
  // manifest fetched from the network at that moment would be the one request that could fail.
  // The icon PNGs deliberately stay out — the OS reads them when the app is INSTALLED, which is
  // an online act, so precaching 180KB of them would tax every start to serve one.
  return {
    entry,
    styles,
    urls: ["/", entry, ...styles, "/favicon.svg", "/icons.svg", MANIFEST_URL],
  };
}

/**
 * A version that changes exactly when the cached bytes change.
 *
 * Not the package version and not a timestamp: the first does not change on every build and the
 * second changes when nothing has, and both are wrong in the same way — the cache is keyed by this,
 * so a version that lies either serves a stale build or throws away a good cache on every deploy.
 */
export function manifestVersion(entries) {
  const digest = createHash("sha256");
  for (const [url, bytes] of entries) {
    digest.update(url);
    digest.update(createHash("sha256").update(bytes).digest());
  }
  return digest.digest("hex").slice(0, 16);
}

/** The worker a consumer writes: import the runtime, hand it the manifest, wire the events. */
function serviceWorkerSource(manifest, version) {
  return `// Generated by scripts/launcher.mjs — do not edit.
import { createPrecache } from "./vendor/multipath-sw.js";

const precache = createPrecache({
  manifest: ${JSON.stringify(manifest)},
  version: ${JSON.stringify(version)},
  // Never answered from cache. The first three are MultiPath's own endpoints — a cached probe would
  // report the latency of the disk. The rest is everything with a session behind it: this worker
  // must never serve data, only the shell that asks for it.
  networkOnly: ["/mt/", "/api/", "/unregister.html"],
});

self.addEventListener("install", (event) => {
  // Take over as soon as the new build is stored, rather than waiting for every tab to close. The
  // alternative leaves a user on the old build for as long as they keep a tab open, which is how a
  // deployed fix appears not to have deployed.
  event.waitUntil(precache.install().then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(precache.activate().then(() => self.clients.claim()));
});

// A navigation to any in-app route is answered with the shell, the way the server's SPA fallback
// does it. Without this only "/" itself would open offline, and every deep link — which is most of
// how this app is actually opened, since every chat and document has its own URL — would fail while
// the whole application sat on disk.
async function shellFor(request) {
  const url = new URL(request.url);
  if (request.mode !== "navigate") return null;
  if (["/mt/", "/api/", "/unregister.html", "/app.html"].some((p) => url.pathname.startsWith(p))) {
    return null;
  }
  const cache = await caches.open(precache.cacheName);
  return (await cache.match("/")) ?? null;
}

self.addEventListener("fetch", (event) => {
  event.respondWith(
    precache
      .handle(event.request)
      .then((response) => response ?? fetch(event.request))
      .catch(async () => (await shellFor(event.request)) ?? Response.error()),
  );
});
`;
}

/**
 * The way out, and it exists before the thing it undoes.
 *
 * A Service Worker caches itself, so a bad one cannot be fixed by deploying a good one to a user
 * who never asks the network again. This page is served from the network by construction (it is in
 * networkOnly), unregisters every worker, deletes every cache, and sends the user to the plain
 * document. It is the difference between a bad deploy being a rollback and being a support case.
 */
const UNREGISTER_HTML = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Reset MicroTeams</title></head>
<body>
<p data-unregister-status>Working…</p>
<script>
(async () => {
  const status = document.querySelector("[data-unregister-status]");
  try {
    const workers = "serviceWorker" in navigator
      ? await navigator.serviceWorker.getRegistrations()
      : [];
    await Promise.all(workers.map((w) => w.unregister()));
    if (window.caches) {
      const names = await caches.keys();
      await Promise.all(names.map((name) => caches.delete(name)));
    }
    status.textContent = "Cleared " + workers.length + " worker(s). Opening the app…";
    status.setAttribute("data-unregister-done", "");
    setTimeout(() => location.replace("/app.html"), 800);
  } catch (error) {
    status.textContent = "Could not clear it: " + error;
  }
})();
</script>
</body>
</html>
`;

/**
 * Put the head tags the built document declared, and the launcher does not, back into the launcher.
 *
 * The manifest link has to be in <head> specifically: browsers only honour `<link rel="manifest">`
 * there, and one placed in the body is ignored silently — the page works, the app simply never
 * becomes installable, with nothing anywhere saying why.
 */
export function withAppHead(html) {
  if (!html.includes("</head>")) throw new Error("launcher document has no </head> to write into");
  const tags = [
    html.includes('rel="manifest"') ? null : `<link rel="manifest" href="${MANIFEST_URL}">`,
    html.includes('name="theme-color"') ? null : `<meta name="theme-color" content="${THEME_COLOR}">`,
  ].filter(Boolean);
  if (tags.length === 0) return html;
  return html.replace("</head>", `${tags.map((t) => `  ${t}`).join("\n")}\n</head>`);
}

export async function build(dist, { registry } = {}) {
  // Idempotent: after the first run the plain document lives in app.html and index.html is the
  // launcher, so reading index.html again would find no entry script — or, worse, overwrite the
  // real document with a launcher. Running a build step twice must not be a mistake anyone can
  // make.
  const source = (await exists(path.join(dist, "app.html")))
    ? path.join(dist, "app.html")
    : path.join(dist, "index.html");
  const original = await readFile(source, "utf8");
  const { entry, styles, urls: manifest } = startupManifest(original);

  // The plain document stays, under a name of its own. It is what /unregister.html sends people
  // back to, and the quickest way to answer "is the worker the problem?" for anyone debugging.
  if (source.endsWith("index.html")) {
    await rename(source, path.join(dist, "app.html"));
  }

  // The launcher REPLACES the built document, so anything index.html declared in <head> is gone
  // unless it is put back here. The manifest link is one of those: without it in the launcher —
  // which is the document an installed app actually opens — the app is not installable at all,
  // and index.html having had the link would prove nothing.
  const launcher = withAppHead(
    buildLauncher({
      appEntry: entry,
      serviceWorker: "/sw.js",
      // The worker imports the runtime, so it is a module. Registered as "classic" it would fail to
      // parse — quietly: the page works from the network and only the cache is never populated.
      serviceWorkerType: "module",
      registry,
      registryUrl: "/mt/lines",
      title: "MicroTeams",
      // The stylesheet has to come with the document: the entry module does not carry it, and
      // without it the app renders unstyled for as long as the app takes to fetch it itself.
      bodyHtml:
        styles.map((href) => `<link rel="stylesheet" href="${href}">`).join("\n") +
        '\n<div id="root"></div>',
    }),
  );
  await writeFile(path.join(dist, "index.html"), launcher, "utf8");

  // Hashed after the launcher exists, because the launcher is in the manifest: the version has to
  // change when the document changes, and the document carries the inlined registry.
  const entries = [];
  for (const url of manifest) {
    const file = url === "/" ? "index.html" : url.replace(/^\//, "");
    entries.push([url, await readFile(path.join(dist, file))]);
  }
  const version = manifestVersion(entries);

  await mkdir(path.join(dist, "vendor"), { recursive: true });
  await copyFile(
    new URL("../node_modules/@micro-teams/multipath/dist/serviceWorker.js", import.meta.url),
    path.join(dist, "vendor", "multipath-sw.js"),
  );
  await writeFile(path.join(dist, "sw.js"), serviceWorkerSource(manifest, version), "utf8");
  await writeFile(path.join(dist, "unregister.html"), UNREGISTER_HTML, "utf8");

  return { manifest, version };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const dist = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "dist");
  const { manifest, version } = await build(dist, {
    // One same-origin line, inline. The app refreshes this from /mt/lines once it is running; what
    // is baked in only has to be enough to start, and "wherever this page came from" always is.
    registry: { lines: [{ id: "origin", url: "", transport: "same-origin", weight: 100 }] },
  });
  console.log(`launcher: version ${version}, precaching ${manifest.length} artefacts`);
}
