/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.api

import app.microteams.model.AgentGitWorkspaceDTO
import app.microteams.model.AgentTokenDTO
import app.microteams.model.ListAgentsResponseDTO
import app.microteams.model.OpenAgentRequestDTO
import app.microteams.model.OpenedAgentDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import kotlin.collections.List
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface AgentApi {

    @Operation(
        tags = ["agent"],
        summary = "Close an agent and its screen",
        operationId = "closeAgent",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Closed")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/agent/{userId}"])
    fun closeAgent(
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["agent"],
        summary =
            "Exchange a screen's durable machine + per-screen tokens (headers X-Microteams-Session and X-Microteams-Screen) for a short-lived JWT that is the agent's own user token. The CLI mints one on demand so every `microteams api` call authorizes as an ordinary user, the same as a human's Bearer token -- there is no separate agent authorization path. ",
        operationId = "exchangeAgentToken",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "A short-lived agent user token",
                    content = [Content(schema = Schema(implementation = AgentTokenDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/agent/token"],
        produces = ["application/json"],
    )
    fun exchangeAgentToken(): ResponseEntity<AgentTokenDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["agent"],
        summary =
            "The calling agent's document-tree git workspace: the URL of its team's git remote and a fresh token to authenticate git against it. The applet's `docs` commands call this (already authenticated as the agent) and hand the token to a `git` subprocess, so the connector binary needs no git knowledge. Authenticated by the agent's own Bearer token. ",
        operationId = "getGitWorkspace",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "The team git remote and a credential for it",
                    content =
                        [Content(schema = Schema(implementation = AgentGitWorkspaceDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/agent/git-workspace"],
        produces = ["application/json"],
    )
    fun getGitWorkspace(): ResponseEntity<AgentGitWorkspaceDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["agent"],
        summary =
            "Agents visible to the caller, narrowed by any combination of the filters below -- this is the only agent enumeration (avatar presence is userId=..., a group's agents is threadId=...). `sid` is present only when the caller may watch the live screen. ",
        operationId = "listAgents",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListAgentsResponseDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/agent"],
        produces = ["application/json"],
    )
    fun listAgents(
        @Parameter(description = "Only these agent users. Non-agents simply do not come back.")
        @Valid
        @RequestParam(value = "userId", required = false)
        userId: kotlin.collections.List<kotlin.Long>?,
        @Parameter(description = "Only agents that are members of this chat thread")
        @Valid
        @RequestParam(value = "threadId", required = false)
        threadId: kotlin.Long?,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "teamId", required = false)
        teamId: kotlin.Long?,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "machineId", required = false)
        machineId: kotlin.String?,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "online", required = false)
        online: kotlin.Boolean?,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "50"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "50")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListAgentsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["agent"],
        summary = "Open an agent (a fresh agent user + its driven screen) on a machine",
        operationId = "openAgent",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Opened",
                    content = [Content(schema = Schema(implementation = OpenedAgentDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/agent"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun openAgent(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        openAgentRequestDTO: OpenAgentRequestDTO
    ): ResponseEntity<OpenedAgentDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["agent"],
        summary =
            "Reboot an agent: end its current screen and relaunch the same driver, in the same cwd, resuming the same session id. The agent user and its group memberships are unchanged; only the backing screen (sid + screen token) is replaced. ",
        operationId = "rebootAgent",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "Rebooted",
                    content = [Content(schema = Schema(implementation = OpenedAgentDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/agent/{userId}/reboot"],
        produces = ["application/json"],
    )
    fun rebootAgent(
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long
    ): ResponseEntity<OpenedAgentDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
