/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.api

import app.microteams.model.AddMemberRequestDTO
import app.microteams.model.ChangeRoleRequestDTO
import app.microteams.model.CreateThreadRequestDTO
import app.microteams.model.ListChatsResponseDTO
import app.microteams.model.ListMessagesResponseDTO
import app.microteams.model.MessageDTO
import app.microteams.model.PostMessageRequestDTO
import app.microteams.model.RenameThreadRequestDTO
import app.microteams.model.ThreadDTO
import app.microteams.model.ThreadDetailDTO
import app.microteams.model.ThreadMemberDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import kotlin.collections.List
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface ChatApi {

    @Operation(
        tags = ["chat"],
        summary = "Add a member to a thread (admin+)",
        operationId = "addThreadMember",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Added")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/chat/{id}/members"],
        consumes = ["application/json"],
    )
    fun addThreadMember(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        addMemberRequestDTO: AddMemberRequestDTO?,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Change a thread member's role (owner only)",
        operationId = "changeThreadMemberRole",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Role changed")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/chat/{id}/members/{userId}"],
        consumes = ["application/json"],
    )
    fun changeThreadMemberRole(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        changeRoleRequestDTO: ChangeRoleRequestDTO?,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Create a thread (caller becomes owner)",
        operationId = "createThread",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = ThreadDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/chat"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createThread(
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        createThreadRequestDTO: CreateThreadRequestDTO?
    ): ResponseEntity<ThreadDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Dissolve a thread (owner only)",
        operationId = "dissolveThread",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Dissolved")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/chat/{id}"])
    fun dissolveThread(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Get thread detail plus members",
        operationId = "getThread",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ThreadDetailDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/chat/{id}"],
        produces = ["application/json"],
    )
    fun getThread(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ThreadDetailDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary =
            "List the current user's chats, each enriched with its members and its last message, most-recent activity first (everything the chat list needs in one call). ",
        operationId = "listChats",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListChatsResponseDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/chat"],
        produces = ["application/json"],
    )
    fun listChats(
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "50"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "50")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListChatsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "List messages with cursor pagination (member+)",
        operationId = "listMessages",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListMessagesResponseDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/chat/{id}/messages"],
        produces = ["application/json"],
    )
    fun listMessages(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "id of the first message on the page (cursor)")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListMessagesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "List a thread's members",
        operationId = "listThreadMembers",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                array =
                                    ArraySchema(
                                        schema = Schema(implementation = ThreadMemberDTO::class)
                                    )
                            )
                        ],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/chat/{id}/members"],
        produces = ["application/json"],
    )
    fun listThreadMembers(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<List<ThreadMemberDTO>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Post a message to a thread (member+); persisted then broadcast via WebSocket",
        operationId = "postMessage",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = MessageDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/chat/{id}/messages"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun postMessage(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        postMessageRequestDTO: PostMessageRequestDTO?,
    ): ResponseEntity<MessageDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Remove a member from a thread (admin+)",
        operationId = "removeThreadMember",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Removed")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/chat/{id}/members/{userId}"])
    fun removeThreadMember(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["chat"],
        summary = "Rename a thread (admin+)",
        operationId = "renameThread",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ThreadDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/chat/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun renameThread(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        renameThreadRequestDTO: RenameThreadRequestDTO?,
    ): ResponseEntity<ThreadDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
