/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.api

import app.microteams.model.LineRegistryDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface LinesApi {

    @Operation(
        tags = ["transport"],
        summary =
            "The network paths that lead to this origin. Public: a client needs it before it can log in, and it describes routes rather than anything about a user. Maintained by hand -- which line is worth keeping is a judgement, not something a health check should decide. ",
        operationId = "listLines",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "The line registry",
                    content = [Content(schema = Schema(implementation = LineRegistryDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/lines"],
        produces = ["application/json"],
    )
    fun listLines(): ResponseEntity<LineRegistryDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
