/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.24.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.api

import app.microteams.model.ApproveEnrollmentRequestDTO
import app.microteams.model.ListMachinesResponseDTO
import app.microteams.model.MachineDTO
import app.microteams.model.PollEnrollmentRequestDTO
import app.microteams.model.PollEnrollmentResponseDTO
import app.microteams.model.RenameMachineRequestDTO
import app.microteams.model.StartEnrollmentRequestDTO
import app.microteams.model.StartEnrollmentResponseDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface MachineApi {

    @Operation(
        tags = ["machine"],
        summary = "A logged-in human approves a pending code and picks the teams it serves.",
        operationId = "approveEnrollment",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "Approved",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/machine/enroll/approve"
        value = [PATH_APPROVE_ENROLLMENT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun approveEnrollment(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        approveEnrollmentRequestDTO: ApproveEnrollmentRequestDTO
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Forget the machine entirely (revokes its token; it must re-enroll)",
        operationId = "forgetMachine",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Forgotten")],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        // "/machine/{id}"
        value = [PATH_FORGET_MACHINE],
    )
    fun forgetMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.String
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/machine/{id}"
        value = [PATH_GET_MACHINE],
        produces = ["application/json"],
    )
    fun getMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.String
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary =
            "Machines visible to the caller, narrowed by any combination of the filters below. Adding a way to slice machines means adding a filter here, never a new endpoint. ",
        operationId = "listMachines",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListMachinesResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/machine"
        value = [PATH_LIST_MACHINES],
        produces = ["application/json"],
    )
    fun listMachines(
        @Parameter(description = "Only machines associated with this team")
        @Valid
        @RequestParam(value = "teamId", required = false)
        teamId: kotlin.Long?,
        @Parameter(description = "Only machines whose control channel is (dis)connected right now")
        @Valid
        @RequestParam(value = "online", required = false)
        online: kotlin.Boolean?,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.String?,
        @Parameter(description = "", schema = Schema(defaultValue = "50"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "50")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListMachinesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Public. The machine polls until a human approves, then receives its token.",
        operationId = "pollEnrollment",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = PollEnrollmentResponseDTO::class)
                            )
                        ],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/machine/enroll/poll"
        value = [PATH_POLL_ENROLLMENT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun pollEnrollment(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        pollEnrollmentRequestDTO: PollEnrollmentRequestDTO
    ): ResponseEntity<PollEnrollmentResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "renameMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "Renamed",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        // "/machine/{id}"
        value = [PATH_RENAME_MACHINE],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun renameMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.String,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        renameMachineRequestDTO: RenameMachineRequestDTO,
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Public. A machine with no token mints a pending code for a human to approve.",
        operationId = "startEnrollment",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = StartEnrollmentResponseDTO::class)
                            )
                        ],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/machine/enroll/start"
        value = [PATH_START_ENROLLMENT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun startEnrollment(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        startEnrollmentRequestDTO: StartEnrollmentRequestDTO
    ): ResponseEntity<StartEnrollmentResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        // for your own safety never directly reuse these path definitions in tests
        const val PATH_APPROVE_ENROLLMENT: String = "/machine/enroll/approve"
        const val PATH_FORGET_MACHINE: String = "/machine/{id}"
        const val PATH_GET_MACHINE: String = "/machine/{id}"
        const val PATH_LIST_MACHINES: String = "/machine"
        const val PATH_POLL_ENROLLMENT: String = "/machine/enroll/poll"
        const val PATH_RENAME_MACHINE: String = "/machine/{id}"
        const val PATH_START_ENROLLMENT: String = "/machine/enroll/start"
    }
}
