/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface ProbeApi {

    @Operation(
        tags = ["transport"],
        summary =
            "Liveness and latency probe. Public, and deliberately the cheapest thing this service can answer: it is called on every line every few seconds, so anything it touched would be touched at that rate too. Not /ping -- that one is authenticated and means something else. ",
        operationId = "probe",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "204",
                    description = "The line works. There is no body, on purpose.",
                )
            ],
    )
    @RequestMapping(method = [RequestMethod.GET], value = ["/probe"])
    fun probe(): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
