/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.api

import app.microteams.model.AddTeamMemberRequestDTO
import app.microteams.model.BindMachineRequestDTO
import app.microteams.model.ChangeRoleRequestDTO
import app.microteams.model.CreateTeamRequestDTO
import app.microteams.model.DocNodeDTO
import app.microteams.model.ListTeamsResponseDTO
import app.microteams.model.MoveDocumentRequestDTO
import app.microteams.model.RenameTeamRequestDTO
import app.microteams.model.TeamDTO
import app.microteams.model.TeamDetailDTO
import app.microteams.model.TeamMemberDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import javax.validation.constraints.NotNull
import kotlin.collections.List
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface TeamApi {

    @Operation(
        tags = ["team"],
        summary = "Add a member to a team (admin+)",
        operationId = "addTeamMember",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Added")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/team/{id}/members"],
        consumes = ["application/json"],
    )
    fun addTeamMember(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        addTeamMemberRequestDTO: AddTeamMemberRequestDTO?,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Associate a machine with this team. The model is symmetric and owner-less.",
        operationId = "bindTeamMachine",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Bound")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/team/{id}/machine"],
        consumes = ["application/json"],
    )
    fun bindTeamMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        bindMachineRequestDTO: BindMachineRequestDTO,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Change a member's role (admin+)",
        operationId = "changeMemberRole",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Role changed")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/team/{id}/members/{userId}"],
        consumes = ["application/json"],
    )
    fun changeMemberRole(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        changeRoleRequestDTO: ChangeRoleRequestDTO?,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Create a team (caller becomes owner)",
        operationId = "createTeam",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = TeamDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/team"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createTeam(
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        createTeamRequestDTO: CreateTeamRequestDTO?
    ): ResponseEntity<TeamDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Delete a file or folder",
        operationId = "deleteDocument",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Deleted")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/team/{id}/document"])
    fun deleteDocument(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @NotNull
        @Parameter(description = "", required = true)
        @Valid
        @RequestParam(value = "path", required = true)
        path: kotlin.String,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Delete a team (owner only)",
        operationId = "deleteTeam",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Deleted")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/team/{id}"])
    fun deleteTeam(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary =
            "Read a team's document tree, one file, its history or a diff — selected by query flags rather than separate endpoints (future views = new flags). ",
        operationId = "getDocument",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = DocNodeDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/team/{id}/document"],
        produces = ["application/json"],
    )
    fun getDocument(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(
            description = "Repo-relative logical path; empty means the repo root",
            schema = Schema(defaultValue = ""),
        )
        @Valid
        @RequestParam(value = "path", required = false, defaultValue = "")
        path: kotlin.String,
        @Parameter(description = "", schema = Schema(defaultValue = "false"))
        @Valid
        @RequestParam(value = "recursive", required = false, defaultValue = "false")
        recursive: kotlin.Boolean,
        @Parameter(description = "", schema = Schema(defaultValue = "false"))
        @Valid
        @RequestParam(value = "content", required = false, defaultValue = "false")
        content: kotlin.Boolean,
        @Parameter(description = "", schema = Schema(defaultValue = "false"))
        @Valid
        @RequestParam(value = "history", required = false, defaultValue = "false")
        history: kotlin.Boolean,
        @Parameter(description = "Commit sha to diff against")
        @Valid
        @RequestParam(value = "diff", required = false)
        diff: kotlin.String?,
    ): ResponseEntity<DocNodeDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Get team detail plus members",
        operationId = "getTeam",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = TeamDetailDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/team/{id}"],
        produces = ["application/json"],
    )
    fun getTeam(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<TeamDetailDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "List a team's members",
        operationId = "listTeamMembers",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                array =
                                    ArraySchema(
                                        schema = Schema(implementation = TeamMemberDTO::class)
                                    )
                            )
                        ],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/team/{id}/members"],
        produces = ["application/json"],
    )
    fun listTeamMembers(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<List<TeamMemberDTO>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "List teams the current user is a member of",
        operationId = "listTeams",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListTeamsResponseDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/team"],
        produces = ["application/json"],
    )
    fun listTeams(
        @Parameter(description = "Only teams where the caller has this role (OWNER/ADMIN/MEMBER)")
        @Valid
        @RequestParam(value = "role", required = false)
        role: kotlin.String?,
        @Parameter(description = "id of the first team on the page (cursor)")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListTeamsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Move / rename a file or folder",
        operationId = "moveDocument",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "Moved",
                    content = [Content(schema = Schema(implementation = DocNodeDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/team/{id}/document"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun moveDocument(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @NotNull
        @Parameter(description = "", required = true)
        @Valid
        @RequestParam(value = "path", required = true)
        path: kotlin.String,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        moveDocumentRequestDTO: MoveDocumentRequestDTO,
    ): ResponseEntity<DocNodeDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Remove a member from a team (admin+)",
        operationId = "removeTeamMember",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Removed")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/team/{id}/members/{userId}"])
    fun removeTeamMember(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true) @PathVariable("userId") userId: kotlin.Long,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Rename a team (admin+)",
        operationId = "renameTeam",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = TeamDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/team/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun renameTeam(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "")
        @Valid
        @RequestBody(required = false)
        renameTeamRequestDTO: RenameTeamRequestDTO?,
    ): ResponseEntity<TeamDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Disassociate a machine from this team",
        operationId = "unbindTeamMachine",
        description = """""",
        responses = [ApiResponse(responseCode = "204", description = "Unbound")],
    )
    @RequestMapping(method = [RequestMethod.DELETE], value = ["/team/{id}/machine/{machineId}"])
    fun unbindTeamMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @PathVariable("machineId")
        machineId: kotlin.String,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["team"],
        summary = "Create or overwrite a file (raw text body)",
        operationId = "writeDocument",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "Written",
                    content = [Content(schema = Schema(implementation = DocNodeDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.PUT],
        value = ["/team/{id}/document"],
        produces = ["application/json"],
        consumes = ["text/plain"],
    )
    fun writeDocument(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @NotNull
        @Parameter(description = "", required = true)
        @Valid
        @RequestParam(value = "path", required = true)
        path: kotlin.String,
        @Parameter(description = "") @Valid @RequestBody(required = false) body: kotlin.String?,
    ): ResponseEntity<DocNodeDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
