/// The one client. Not an API layer — there is no API layer any more.
///
/// `packages/mt_api` is generated by openapi-generator from the repo-root MicroTeams-API.yml, the
/// same contract the backend generates its Api interfaces from, so `client.chat.listChats()` and
/// the backend's `ChatApi.listChats` are two ends of one definition. Nothing hand-written wraps it:
/// a controller calls the generated method and gets the generated type. What used to sit in between
/// — a `` every caller had to remember, a bespoke cache with keys every screen invented —
/// is gone, because both were doing badly what something else does properly.
///
/// What is left here is only what a contract cannot say: where the server is, who we are, what an
/// error means, and which network line to leave by. Those are four interceptors and an adapter,
/// stacked in the one order that works:
///
///   1. bearer token          — who we are
///   2. idempotency key       — minted once per logical write, BEFORE a line is chosen
///   3. cache recording       — what a successful GET returned, for the next cold start
///   4. error translation     — DioException in, MtError out, so nothing above ever sees Dio
///   5. MultiPath adapter     — hedged reads, write failover, underneath all of the above
///
/// The token and the key are attached above line selection deliberately: authentication is about
/// the caller, and a key that changed per line would defeat the de-duplication it exists for.
library;

import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:mt_api/mt_api.dart';
import 'package:multipath/multipath.dart' as mp;

import 'errors.dart';
import 'lines.dart';
import 'multipath_adapter.dart';

/// Asked for a fresh access token after a 401. Returns null if the session is really over.
typedef Reauthorize = Future<String?> Function();

class MtClient {
  /// [adapter] replaces the transport underneath MultiPath. Tests pass a fake one so a controller
  /// can be driven against canned responses — the alternative is testing controllers against a live
  /// server, which is how a suite ends up covering only the happy path.
  MtClient({
    required String baseUrl,
    required Reauthorize reauthorize,
    mp.LineManager? lines,
    mp.RequestCache? cache,
    HttpClientAdapter? adapter,
  }) : _reauthorize = reauthorize,
       lines = lines ?? mp.LineManager(registry: sameOriginOnly()),
       cache = cache ?? mp.RequestCache(),
       _dio = Dio(
         BaseOptions(
           baseUrl: baseUrl,
           // nt returns raw DTOs and serializes errors as {code, message, error}. Read the body
           // whatever the status, then translate — see the error interceptor below.
           validateStatus: (_) => true,
           extra: const {'withCredentials': true},
         ),
       ) {
    _dio.httpClientAdapter = MultiPathAdapter(
      manager: this.lines,
      inner: adapter ?? _dio.httpClientAdapter,
    );
    _dio.interceptors.addAll([
      InterceptorsWrapper(onRequest: _attachToken),
      IdempotencyInterceptor(),
      InterceptorsWrapper(onResponse: _recordAndTranslate, onError: _asMtError),
    ]);
  }

  final Dio _dio;

  /// The one client, for the two things that are not API calls: probing a line, and anything else
  /// that has to reach a line rather than an endpoint.
  Dio get dio => _dio;
  final Reauthorize _reauthorize;

  /// Which lines exist, what is known about each, and therefore which one a request leaves by.
  final mp.LineManager lines;

  /// What the same request returned last time — offered ALONGSIDE the real answer, never in place
  /// of it. Every request still goes out; this is only something a screen may paint while waiting.
  final mp.RequestCache cache;

  /// Kept in lockstep with the session by the auth layer, so a screen can call a typed API method
  /// without threading a token through every signature.
  String? accessToken;

  ChatApi get chat => ChatApi(_dio);
  TeamApi get team => TeamApi(_dio);
  MachineApi get machine => MachineApi(_dio);
  AgentApi get agent => AgentApi(_dio);
  TransportApi get transport => TransportApi(_dio);

  /// What a previous run got for this request, decoded, or null.
  ///
  /// Keyed by the request itself rather than by a name a screen chooses, which is what stops two
  /// screens inventing two names for the same data and never sharing it — and what lets the cache
  /// be filled automatically below rather than by every caller remembering to.
  T? cached<T>(String method, String path) =>
      cache.get<T>(mp.RequestCache.keyFor(method, path));

  void _attachToken(RequestOptions options, RequestInterceptorHandler handler) {
    final token = accessToken;
    if (token != null && token.isNotEmpty) {
      options.headers['Authorization'] = 'Bearer $token';
    }
    handler.next(options);
  }

  Future<void> _recordAndTranslate(
    Response<Object?> response,
    ResponseInterceptorHandler handler,
  ) async {
    final status = response.statusCode ?? 0;
    if (status >= 200 && status < 300) {
      _remember(response);
      return handler.next(response);
    }

    if (status == 401 && response.requestOptions.extra['mt.retried'] != true) {
      final fresh = await _reauthorize();
      if (fresh != null && fresh.isNotEmpty) {
        accessToken = fresh;
        final options = response.requestOptions
          ..headers['Authorization'] = 'Bearer $fresh'
          ..extra['mt.retried'] = true;
        try {
          final retried = await _dio.fetch<Object?>(options);
          return handler.resolve(retried);
        } catch (_) {
          // Fall through: a failed retry is still a failure.
        }
      }
    }

    handler.reject(_translate(response), true);
  }

  /// Every successful GET, remembered. Automatic on write and explicit on read, because forgetting
  /// to store is invisible and forgetting to read is not.
  void _remember(Response<Object?> response) {
    final options = response.requestOptions;
    if (options.method.toUpperCase() != 'GET') return;
    final data = response.data;
    if (data == null) return;
    cache.set(
      mp.RequestCache.keyFor('GET', _pathOf(options.uri)),
      // The decoded body, not the object: what comes back is a generated model on the way out of
      // the client but a Map here, and a Map is what survives being written to disk and read again.
      data is String ? _tryDecode(data) : data,
    );
  }

  Object? _tryDecode(String body) {
    try {
      return jsonDecode(body);
    } catch (_) {
      return body;
    }
  }

  String _pathOf(Uri uri) =>
      '${uri.path}${uri.hasQuery ? '?${uri.query}' : ''}';

  void _asMtError(DioException error, ErrorInterceptorHandler handler) {
    if (error is MtError) return handler.next(error);
    // No response: the network, not the server. Status 0 so a screen can tell the two apart.
    handler.next(
      MtError(
        error.message ?? 'network error',
        0,
        request: error.requestOptions,
      ),
    );
  }

  MtError _translate(Response<Object?> response) {
    final status = response.statusCode ?? 0;
    final body = response.data;
    if (body is Map<String, Object?>) {
      final message = body['message'];
      final code = body['code'];
      return MtError(
        message is String ? message : 'HTTP $status',
        status,
        code: code is num ? code.toInt() : null,
        request: response.requestOptions,
      );
    }
    return MtError('HTTP $status', status, request: response.requestOptions);
  }
}
