// The layering rule, enforced by reading the source.
//
// The React client had to grow a custom lint for exactly this (PR #162): screens had accumulated
// their own API calls, so the same fetch existed in the phone layout and the desktop layout and
// drifted apart. The rule that fixed it is simple enough to check with a regex, and a rule that is
// checked is a rule that survives a rewrite.
//
// A screen renders state and reports intent. It does not fetch, does not hold a client, and does
// not subscribe. Everything that talks to a server lives in a controller behind a provider.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Files that are allowed to know the network exists.
const _plumbing = {
  'lib/src/mt/client.dart',
  'lib/src/auth/auth_api.dart',
  'lib/src/app_providers.dart',
  'lib/src/core/config.dart',
  'lib/src/updates/socket.dart',
};

List<File> _dartFiles(String dir) => Directory(dir)
    .listSync(recursive: true)
    .whereType<File>()
    .where((f) => f.path.endsWith('.dart'))
    .toList();

void main() {
  test('no screen talks to a server', () {
    final offenders = <String>[];

    for (final file in _dartFiles('lib/src')) {
      final path = file.path;
      if (!path.endsWith('_screen.dart')) continue;
      final source = file.readAsStringSync();

      if (source.contains('mtCall(')) {
        offenders.add('$path calls mtCall — move the fetch into a controller');
      }
      if (source.contains("mt/client.dart")) {
        offenders.add('$path imports the nt client directly');
      }
      if (source.contains('watchTopic(')) {
        offenders.add(
          '$path subscribes to a topic — a screen that can hold data is a '
          'second path to the pixels',
        );
      }
    }

    expect(offenders, isEmpty, reason: offenders.join('\n'));
  });

  test('only the plumbing knows where the server is', () {
    final offenders = <String>[];

    for (final file in _dartFiles('lib/src')) {
      final path = file.path;
      if (_plumbing.contains(path)) continue;
      final source = file.readAsStringSync();
      // A hostname or a hard-coded /mt path anywhere else means a request that cannot be routed,
      // re-pointed, or tested against a fake.
      if (RegExp(r"'https?://").hasMatch(source)) {
        offenders.add('$path hard-codes a URL');
      }
    }

    expect(offenders, isEmpty, reason: offenders.join('\n'));
  });

  test('the generated client cannot be committed, so it cannot be edited', () {
    // The strongest available guarantee that nobody "just fixes" a generated model: the whole
    // package is ignored, so an edit cannot survive a checkout. Same arrangement as
    // frontend/src/api on the TypeScript side.
    final ignore = File('.gitignore').readAsStringSync();
    expect(
      ignore.contains('packages/mt_api/'),
      isTrue,
      reason:
          'app/.gitignore must ignore packages/mt_api/ — it is generated by tool/codegen.sh from '
          'the repo-root contract, and a committed copy is one that can drift from it',
    );
  });
}
